[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
via_ir = false



remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@chainlink/contracts-ccip/=lib/chainlink-ccip/chains/evm/contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts@5.0.2/=lib/openzeppelin-contracts/contracts/",
]
